### ISSUE TITLE
Touchscreen broken on SHPI zero

### ISSUE THREAD

**Issue by errrrata** [shpi/zero_main_application#6]
f85cab46684a7e33b1be63f8abf4ce08cb9a2499 breaks touchscreen on SHPI Zero.

On first run, I also got the following (haven't seen it on consequent runs):

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pi/zero_main_application/shpi/core/peripherals.py", line 109, in touchloop
    if touch_startx:
UnboundLocalError: local variable 'touch_startx' referenced before assignment
```

**Comment by shpi** [comment]
solved.
